<?php
/**
 * Database Setup Script
 * 
 * This script helps set up the database for the Digital Archive Management System.
 * Run this script once to create the database structure.
 */

require_once '../config/config.php';

try {
    // Connect to MySQL without selecting a database
    $pdo = new PDO("mysql:host=" . DB_HOST, DB_USER, DB_PASS);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "<h2>Digital Archive Management System - Database Setup</h2>";
    
    // Create database if it doesn't exist
    $pdo->exec("CREATE DATABASE IF NOT EXISTS " . DB_NAME);
    echo "<p>✓ Database '" . DB_NAME . "' created successfully.</p>";
    
    // Select the database
    $pdo->exec("USE " . DB_NAME);
    
    // Read and execute the schema file
    $schema = file_get_contents(__DIR__ . '/../database/schema.sql');
    
    // Split the schema into individual queries
    $queries = explode(';', $schema);
    
    foreach ($queries as $query) {
        $query = trim($query);
        if (!empty($query)) {
            $pdo->exec($query);
        }
    }
    
    echo "<p>✓ Database tables created successfully.</p>";
    echo "<p>✓ Default data inserted.</p>";
    
    echo "<div style='background: #d4edda; border: 1px solid #c3e6cb; color: #155724; padding: 1rem; margin: 1rem 0; border-radius: 5px;'>";
    echo "<h3>Setup Complete!</h3>";
    echo "<p>Your database has been set up successfully. You can now:</p>";
    echo "<ul>";
    echo "<li>Login with: <strong>admin</strong> / <strong>admin123</strong></li>";
    echo "<li>Start uploading and managing videos</li>";
    echo "<li>Create additional user accounts</li>";
    echo "</ul>";
    echo "<p><a href='../index.php' style='color: #155724; font-weight: bold;'>Go to Application →</a></p>";
    echo "</div>";
    
} catch (PDOException $e) {
    echo "<div style='background: #f8d7da; border: 1px solid #f5c6cb; color: #721c24; padding: 1rem; margin: 1rem 0; border-radius: 5px;'>";
    echo "<h3>Setup Error</h3>";
    echo "<p>Error setting up database: " . $e->getMessage() . "</p>";
    echo "<p>Please check your database configuration in config/config.php and ensure:</p>";
    echo "<ul>";
    echo "<li>MySQL server is running</li>";
    echo "<li>Database credentials are correct</li>";
    echo "<li>User has permission to create databases</li>";
    echo "</ul>";
    echo "</div>";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Setup - Digital Archive Management</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 2rem auto;
            padding: 2rem;
            background-color: #f4f6f9;
        }
        
        h2 {
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 0.5rem;
        }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>